# Generated by Django 4.2.7 on 2024-01-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Herbivore', 'Herbivore'), ('Carnivore', 'Carnivore')], max_length=20)),
                ('sound', models.CharField(max_length=100)),
                ('extra_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
